### ISSUE TITLE
Module not found: Can't resolve 'react-infinite-ticker'

### ISSUE THREAD

**Issue by dparkar** [g12i/react-infinite-ticker#1]
After doing `npm i react-infinite-ticker` and importing VerticalTicker by : `import { VerticalTicker } from "react-infinite-ticker";` seeing the following error : 

> Module not found: Can't resolve 'react-infinite-ticker'

Appreciate any suggestions.

**Comment by g12i** [comment]
Hi @dparkar .

Sorry for the delay. There was indeed a problem with the module. It's been fixed in c9fdd100af8ddde77ab99fc753d9f3e8aa74d2a7

Please give it a go `npm i react-infinite-ticker@1.0.0-rc.1` and let me know if it works for you.

Thanks
