### ISSUE TITLE
support typescript

### ISSUE THREAD

**Issue by StringKe** [g12i/react-infinite-ticker#6]
Add typescript type definition file

<img width="210" alt="CleanShot 2022-06-14 at 12 09 11@2x" src="https://user-images.githubusercontent.com/31089228/173491470-7bff8930-2b7b-4416-918d-599b40295c98.png">

Recognizing imports in `webstorm` is `.umd.js` doesn't seem to recognize the correct type

<img width="1287" alt="CleanShot 2022-06-14 at 12 09 59@2x" src="https://user-images.githubusercontent.com/31089228/173491572-679fc207-0eca-4238-b2dc-85a61167d8a0.png">

**Comment by g12i** [comment]
It appears that it points to a [wrong file in package.json](https://github.com/g12i/react-infinite-ticker/blob/master/package.json#L17)

I'll try to fix it today

**Comment by g12i** [comment]
Fix in 085139207a3c7eb4a6ac8ae75d82c7d33f95618b please update to `2.1.1`
