### ISSUE TITLE
Glitchy following iterations

### ISSUE THREAD

**Issue by almapowell** [g12i/react-infinite-ticker#7]
I'm not quit sure why this is happening, but is a delay and white space before the next iteration appears. (Sped it up to get to the point)

https://user-images.githubusercontent.com/49799618/218117404-b60f9084-8cc0-4b91-8926-29d2da0befcf.mov

I copied and pasted the exact code.

![Screenshot 2023-02-10 at 8 33 04 AM](https://user-images.githubusercontent.com/49799618/218117511-e38e6cde-3996-4455-829f-0eec1118f46e.png)

**Comment by g12i** [comment]
Hi, the current implementation 
- Copies children passed to a Ticker component
- Places them next to the original (or below for Vertical)
- Shuffles them around like so:

![Wojciech playground§](https://user-images.githubusercontent.com/7079786/218144644-b19b5fcc-34fe-4285-aa89-56b0dc2ea713.jpg)

In your case there isn't enough content to fill the container (viewport in this case).

I'd suggest copying it yourself, like so:

```ts
const content = (
  <>
    <div>Put anything you want</div>
    <img src="/images/as/well.png" />
    <h1>All good</h1>
  </>
);

return (
  <VerticalTicker duration={15000}>
    {content}
    {content}
  </VerticalTicker>
)
```

Until you fit your container's width.

**Comment by almapowell** [comment]
Yep makes sense. Thank you!
